
import React, { useEffect, useState } from 'react';
import { Asset } from '../types';
import { X, Bot, Sparkles, BarChart2 } from 'lucide-react';
import { getMarketOverview } from '../services/geminiService';

interface MarketAnalysisModalProps {
  assets: Asset[];
  onClose: () => void;
  brandColor: string;
}

const MarketAnalysisModal: React.FC<MarketAnalysisModalProps> = ({ assets, onClose, brandColor }) => {
  const [analysis, setAnalysis] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchAnalysis = async () => {
      setIsLoading(true);
      const text = await getMarketOverview(assets);
      setAnalysis(text);
      setIsLoading(false);
    };
    fetchAnalysis();
  }, [assets]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-2xl shadow-2xl relative overflow-hidden flex flex-col max-h-[80vh]">
        
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-slate-900 z-10">
           <div className="flex items-center gap-3">
             <div className="p-2 bg-purple-500/20 rounded-lg text-purple-400">
               <Bot size={24} />
             </div>
             <div>
               <h2 className="text-xl font-bold text-white flex items-center gap-2">
                 AI Market Intelligence <Sparkles size={16} className="text-yellow-400" />
               </h2>
               <span className="text-slate-400 text-xs">Real-time analysis of {assets.length} assets</span>
             </div>
           </div>
           <button onClick={onClose} className="text-slate-500 hover:text-white transition-colors">
             <X size={24} />
           </button>
        </div>

        {/* Content */}
        <div className="p-8 overflow-y-auto custom-scrollbar">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center py-12 space-y-4">
               <div className="relative">
                 <div className="w-12 h-12 rounded-full border-4 border-slate-700 border-t-purple-500 animate-spin"></div>
                 <Bot size={20} className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-purple-500" />
               </div>
               <p className="text-slate-400 animate-pulse">Generating strategic report...</p>
            </div>
          ) : (
            <div className="space-y-6">
               <div className="prose prose-invert max-w-none">
                 {analysis.split('\n').map((paragraph, idx) => (
                   paragraph.trim() && (
                     <p key={idx} className="text-slate-300 leading-relaxed text-lg mb-4">
                       {paragraph}
                     </p>
                   )
                 ))}
               </div>
               
               <div className="grid grid-cols-2 gap-4 mt-6">
                  <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                    <h4 className="text-xs font-bold text-slate-500 uppercase mb-2">Dominant Trend</h4>
                    <div className="flex items-center gap-2">
                       <BarChart2 size={20} className="text-green-400" />
                       <span className="text-white font-medium">Accumulation Phase</span>
                    </div>
                  </div>
                  <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                    <h4 className="text-xs font-bold text-slate-500 uppercase mb-2">Volatility Index</h4>
                    <div className="flex items-center gap-2">
                       <div className="w-full bg-slate-700 h-2 rounded-full overflow-hidden">
                         <div className="bg-yellow-500 h-full w-[65%]"></div>
                       </div>
                       <span className="text-yellow-500 font-bold text-sm">65</span>
                    </div>
                  </div>
               </div>
            </div>
          )}
        </div>
        
        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-900/50 text-center">
          <p className="text-xs text-slate-500">
            Analysis generated by Gemini 2.5 Flash. Not financial advice.
          </p>
        </div>
      </div>
    </div>
  );
};

export default MarketAnalysisModal;
